provider: "http://dloai.lib.utk.edu/cgi-bin/XMLFile/dlmodsoai/oai.pl"
collections:
- acwiley
- bcpl
- derris
- egypt
- gamble
- heilman
- kefauver
- kintner
- mpabaker
- roth
- sanborn
- volvoices
- vpmoore